### ISSUE TITLE
dev-loader broken

### ISSUE THREAD

**Issue by siddharthvp** [ptsgrn/twinkle-thuncyc#2]
[This patch](https://github.com/wikimedia-gadgets/twinkle-starter/pull/22/commits/484144e21ba0fa58f1bcb7d41782fe8c978f88f4) would need to be applied for `npm start` command to work correctly. This was broken due to a recent MediaWiki change.

**Comment by ptsgrn** [comment]
Thank you for reached out to me — fixed with c561f64
